### PR TITLE
Boilerplate Components

### PR DESCRIPTION
**Pull request by bengammon**
Components from the following issue have been added: https://github.com/EtchUK/Etch.OrchardCore.ThemeBoilerplate/issues/31

Still to do:

- [x] Add JS to menu
- - [x] Mobile menu toggle
- - [x] Tap to open/close nav items with sub menus

### CODE REVIEW

**Comment by peterkeating** [comment]
@bengammon Can you add a checklist to your PR that includes the bits that still need to be done, I'm thinking about the JavaScript here.

**Comment by bengammon** [comment]
@peterkeating added a checklist

**Comment by peterkeating** [comment]
@bengammon Added the JavaScript for the menu. Currently the nav doesn't show when toggling the menu visibility via the "Menu" button. I've set it up so when the menu should be visible the `html` element has `is-nav-visible` applied to it.

**Comment by peterkeating** [comment]
@bengammon We're missing the `425` break point for the hero background image, unless this is intentional?

**Comment by bengammon** [comment]
> @bengammon We're missing the `425` break point for the hero background image, unless this is intentional?

Not intentional, no. The aspect ratio for the `425` will be the same as `768` but for completeness I will need to add this in.

**Comment by peterkeating** [comment]
@bengammon Noticed there are a couple theme values being referenced that don't exist.

- fontSize.small
- color.validationError

This are highlighted as warnings when running the webpack build.

**Comment by bengammon** [comment]
@peterkeating I have pushed a change to fix the webpack warnings

**Comment by peterkeating** [comment]
@bengammon Nice work on removing the warnings.

Only things remaining are:
[ ] Add missing `425` image
[ ] Cater for mobile menu button being clicked and the menu becoming visible

**Comment by bengammon** [comment]
@peterkeating Those two final things have now been addressed. Over to you :)

**Comment by peterkeating** [comment]
Nice work, I'll have another look through tomorrow morning and then we can get this merged in and deployed a new `v0.3.0` release.

Great work @bengammon !

**Pull request merged**
