### PR TITLE
Checkboxes and radios

### PR DESCRIPTION
**Pull request by Newnab**
Adds checkbox/radio widgets (See widgets module for markup: https://github.com/EtchUK/Etch.OrchardCore.Widgets/pull/50) and applies some styling improvements from a recent project.

### CODE REVIEW

**Review by peterkeating — CHANGES_REQUESTED** [review]
Be great if the checkboxes were also available in the basic recipe.

**Comment by Newnab** [comment]
I don't think any of the form widgets are available in the Basic recipe by default currently. If we're putting Checkboxes in there, presumably we should add the others? e.g Form, Input, Select, Textarea, Button?

**Comment by peterkeating** [comment]
> I don't think any of the form widgets are available in the Basic recipe by default currently. If we're putting Checkboxes in there, presumably we should add the others? e.g Form, Input, Select, Textarea, Button?

Basic form content types are provided via `OrchardCore.Forms`, by enabling that feature we get all those widgets.

**Comment by peterkeating** [comment]
Cherry picked the commits on to `v0.7.0` and also added the new widgets and the form ones to the basic recipe.

**Pull request closed without merging**
