### PR TITLE
Updated the 'target-ie' mixin to also target Edge

### PR DESCRIPTION
**Pull request by bengammon**
- Rather than have an additional mixin for Edge, bundling them together means we can target IE and Edge with one mixin
- Fixed a typo on the word 'targeting'

### CODE REVIEW

**Comment by peterkeating** [comment]
@bengammon Would it be better to add a new mixin `target-ie-edge` that contains this update. Keep `target-ie` as it was, think it would be useful to target only Internet Explorer.

**Comment by bengammon** [comment]
I have split the mixin in two. This is a better approach as it gives us more control

**Comment by peterkeating** [comment]
@bengammon Would there ever be an occasion where you think we would need to target IE **and** Edge? If yes, how would you do that with these mixins?

**Comment by bengammon** [comment]
@peterkeating I originally had the two mixins bundled together because of a lack of support for clip-path/image-mask in IE/Edge. That's quite specific to the project it was used in, so they should be kept separate by default.

As for using two mixins at the same time, it looks like Sass won't allow you to do the following:

`
.test {
    @include target-edge,
    @include target-ie {
        color: green;
    }
}
`

But you can create a mixin that includes other mixins. Here's an example that I put together: https://codepen.io/bengammon/full/VJaGeN

Thoughts?

**Comment by peterkeating** [comment]
@bengammon Yea, let's go with what you have in your codepen example, which is essentially what you had in your first commit for this PR.

**Pull request merged**
