### PR TITLE
Add Rellax Parallax library to package.json and index.ts

### PR DESCRIPTION
**Pull request by JoeBerkley**
@bengammon asked me to add parallax to one of our client projects, and after getting it set up, Ben said this might be something useful going forward, so it would make sense to have it in our boilerplate.

This PR will add the library [Rellax](https://github.com/dixonandmoe/rellax) to the boilerplate, which is a lightweight library for managing parallax easily. We settled on using the class name `parallax` over `rellax` as their docs suggest, as its easier to know whats going on if you're not aware of Rellax.

### CODE REVIEW

**Comment by peterkeating** [comment]
@JoeBerkley How much weight does it add the the JavaScript bundle? Thought is we might be adding a bunch of redundant JavaScript if parallax isn't used. Might be better if it was disabled by default but can easily be enabled when needed.

**Comment by JoeBerkley** [comment]
> 
> 
> @JoeBerkley How much weight does it add the the JavaScript bundle? Thought is we might be adding a bunch of redundant JavaScript if parallax isn't used. Might be better if it was disabled by default but can easily be enabled when needed.

It adds 36kb, going from 459KB to 495KB. @bengammon suggested that we'll try using parallax more going forward, and as the weight isnt much higher and disabling it is easy its probably better to have it enabled, but disabled when not needed?

**Comment by peterkeating** [comment]
Wow our JavaScript bundle is 459kb? Is that the production version (i.e. compressed)?

**Comment by JoeBerkley** [comment]
> 
> 
> Wow our JavaScript bundle is 459kb? Is that the production version (i.e. compressed)?

No, youre right, that was the normal develop watch! The production one is 54KB without and 59KB with, so only a 5KB difference.

**Pull request merged**
